apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  selector:
    app: webui
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
